export const QUERY_KEYS = {
  All_DESTINATION: 'all-destination',
  SINGLE_DESTINATION_PACKAGES: 'single-destination-packages',
  SINGLE_PACKAGES: 'single-packages',
  ALL_PACKAGES: 'all-packages',
  NEW_BOOKING: 'new-booking',
  MY_BOOKINGS: 'my-bookings',
  SINGLE_DESTINATION: 'single-destination',
  GALLERY_IMAGES: 'gallery-images',
  ADMIN_BOOKINGS_LIST: 'admin-bookings-list',
  SINGLE_BOOKING: 'single-booking',
  ADMIN_DASHBOARD_STATS: 'admin-dashboard-stats',
  USER_DASHBOARD_STATS: 'user-dashboard-stats',
  ADMIN_USER_LIST: 'admin-user-list',
  USER_WISHLIST: 'user-wishlist',
  SINGLE_PACKAGE_WITH_DEPARTURES: 'single-package-with-departures',
  ADMIN_PACKAGES_WITH_GALLERY: 'admin-packages-with-gallery',
  ADMIN_SINGLE_PACKAGE_WITH_GALLERY: 'admin-single-package-with-gallery',
  ADMIN_PACKAGES_LIST: 'admin-packages-list',
  FESTIVAL_PACKAGES: 'festival-packages',
  PACKAGE_REVIEWS: 'package-reviews',
  ADMIN_REVIEWS: 'admin-reviews',
};
